name: matthall.net
description: Matt Hall. Front end web developer living in London.
markdown: redcarpet
pygments: true
encoding: utf-8
timezone: Europe/London
exclude:
 - app.yaml
 - grunt
 - node_modules
 - Gruntfile.js
 - package.json
 - scss
 - README.md
