runtime: python37
default_expiration: 1h

handlers:
- url: /
  static_files: index.html
  upload: index\.html
  secure: always

- url: /robots.txt
  static_files: robots.txt
  upload: robots\.txt
  secure: always
